/*
 * Vencord, a Discord client mod
 * Copyright (c) 2026 LawyerCord contributors
 * SPDX-License-Identifier: GPL-3.0-or-later
 */

// Generated by scripts/generatePrivacyInventory.mjs. Do not edit manually.

export const SOURCE_PRIVACY_INVENTORY: Record<string, {
    externalDomains: string[];
    storage: string[];
    permissions: string[];
}> = {
    "src/plugins/_api": {
        "externalDomains": [
            "badge.equicord.org",
            "badges.vencord.dev",
            "cdn.discordapp.com",
            "equicord.org",
            "github.com",
            "www.gnu.org"
        ],
        "storage": [],
        "permissions": [
            "Network access",
            "Open external applications or URLs"
        ]
    },
    "src/plugins/_core": {
        "externalDomains": [
            "discord.com",
            "github.com",
            "media.tenor.com",
            "www.gnu.org"
        ],
        "storage": [],
        "permissions": [
            "Discord write operations",
            "Network access"
        ]
    },
    "src/plugins/accountPanelServerProfile": {
        "externalDomains": [],
        "storage": [],
        "permissions": []
    },
    "src/plugins/alwaysAnimate": {
        "externalDomains": [
            "www.gnu.org"
        ],
        "storage": [],
        "permissions": []
    },
    "src/plugins/alwaysExpandRoles": {
        "externalDomains": [
            "www.gnu.org"
        ],
        "storage": [],
        "permissions": []
    },
    "src/plugins/alwaysTrust": {
        "externalDomains": [
            "www.gnu.org"
        ],
        "storage": [],
        "permissions": []
    },
    "src/plugins/anonymiseFileNames": {
        "externalDomains": [
            "www.gnu.org",
            "www.w3.org"
        ],
        "storage": [],
        "permissions": []
    },
    "src/plugins/appleMusic.desktop": {
        "externalDomains": [
            "itunes.apple.com",
            "song.link"
        ],
        "storage": [],
        "permissions": [
            "Network access"
        ]
    },
    "src/plugins/arRPC.web": {
        "externalDomains": [
            "github.com",
            "www.gnu.org"
        ],
        "storage": [],
        "permissions": [
            "Network access"
        ]
    },
    "src/plugins/autoDndWhilePlaying.discordDesktop": {
        "externalDomains": [],
        "storage": [],
        "permissions": []
    },
    "src/plugins/betterFolders": {
        "externalDomains": [
            "www.gnu.org"
        ],
        "storage": [],
        "permissions": []
    },
    "src/plugins/betterGifAltText": {
        "externalDomains": [
            "www.gnu.org"
        ],
        "storage": [],
        "permissions": [
            "Local filesystem access"
        ]
    },
    "src/plugins/betterGifPicker": {
        "externalDomains": [],
        "storage": [],
        "permissions": []
    },
    "src/plugins/betterRoleContext": {
        "externalDomains": [],
        "storage": [],
        "permissions": [
            "Clipboard access"
        ]
    },
    "src/plugins/betterRoleDot": {
        "externalDomains": [
            "www.gnu.org"
        ],
        "storage": [],
        "permissions": []
    },
    "src/plugins/betterSessions": {
        "externalDomains": [
            "www.gnu.org"
        ],
        "storage": [
            "Browser or plugin data store",
            "Persistent local storage"
        ],
        "permissions": [
            "Local filesystem access",
            "Network access"
        ]
    },
    "src/plugins/betterSettings": {
        "externalDomains": [],
        "storage": [],
        "permissions": []
    },
    "src/plugins/betterUploadButton": {
        "externalDomains": [
            "www.gnu.org"
        ],
        "storage": [],
        "permissions": []
    },
    "src/plugins/biggerStreamPreview": {
        "externalDomains": [
            "www.gnu.org"
        ],
        "storage": [],
        "permissions": []
    },
    "src/plugins/blurNsfw": {
        "externalDomains": [],
        "storage": [],
        "permissions": []
    },
    "src/plugins/callTimer": {
        "externalDomains": [],
        "storage": [],
        "permissions": []
    },
    "src/plugins/characterCounter": {
        "externalDomains": [],
        "storage": [],
        "permissions": []
    },
    "src/plugins/clearURLs": {
        "externalDomains": [
            "raw.githubusercontent.com",
            "www.gnu.org"
        ],
        "storage": [],
        "permissions": [
            "Network access"
        ]
    },
    "src/plugins/clientTheme": {
        "externalDomains": [
            "css-tricks.com",
            "www.w3.org"
        ],
        "storage": [],
        "permissions": [
            "Network access"
        ]
    },
    "src/plugins/colorSighted": {
        "externalDomains": [
            "www.gnu.org"
        ],
        "storage": [],
        "permissions": []
    },
    "src/plugins/consoleJanitor": {
        "externalDomains": [
            "github.com"
        ],
        "storage": [],
        "permissions": []
    },
    "src/plugins/consoleShortcuts": {
        "externalDomains": [
            "www.gnu.org"
        ],
        "storage": [],
        "permissions": [
            "Discord message access"
        ]
    },
    "src/plugins/copyEmojiMarkdown": {
        "externalDomains": [],
        "storage": [],
        "permissions": []
    },
    "src/plugins/copyFileContents": {
        "externalDomains": [],
        "storage": [],
        "permissions": []
    },
    "src/plugins/copyStickerLinks": {
        "externalDomains": [
            "www.gnu.org"
        ],
        "storage": [],
        "permissions": [
            "Open external applications or URLs"
        ]
    },
    "src/plugins/copyUserURLs": {
        "externalDomains": [
            "discord.com",
            "www.gnu.org"
        ],
        "storage": [],
        "permissions": [
            "Clipboard access"
        ]
    },
    "src/plugins/crashHandler": {
        "externalDomains": [
            "www.gnu.org"
        ],
        "storage": [
            "Browser or plugin data store"
        ],
        "permissions": []
    },
    "src/plugins/customCommands": {
        "externalDomains": [
            "www.gnu.org"
        ],
        "storage": [],
        "permissions": []
    },
    "src/plugins/customIdle": {
        "externalDomains": [],
        "storage": [],
        "permissions": []
    },
    "src/plugins/customRPC": {
        "externalDomains": [
            "discord.com",
            "i.imgur.com",
            "imgur.com",
            "media.tenor.com",
            "www.gnu.org"
        ],
        "storage": [],
        "permissions": []
    },
    "src/plugins/dearrow": {
        "externalDomains": [
            "dearrow-thumb.ajay.app",
            "dearrow.ajay.app",
            "sponsor.ajay.app",
            "www.w3.org"
        ],
        "storage": [],
        "permissions": [
            "Network access"
        ]
    },
    "src/plugins/decor": {
        "externalDomains": [
            "decor.fieryflames.dev",
            "discord.gg",
            "github.com",
            "ugc.decor.fieryflames.dev"
        ],
        "storage": [
            "Browser or plugin data store",
            "Persistent local storage"
        ],
        "permissions": [
            "Clipboard access",
            "Network access"
        ]
    },
    "src/plugins/devCompanion.dev": {
        "externalDomains": [
            "www.gnu.org"
        ],
        "storage": [],
        "permissions": [
            "Network access"
        ]
    },
    "src/plugins/disableCallIdle": {
        "externalDomains": [
            "www.gnu.org"
        ],
        "storage": [],
        "permissions": []
    },
    "src/plugins/dontRoundMyTimestamps": {
        "externalDomains": [
            "www.gnu.org"
        ],
        "storage": [],
        "permissions": []
    },
    "src/plugins/experiments": {
        "externalDomains": [],
        "storage": [],
        "permissions": []
    },
    "src/plugins/expressionCloner": {
        "externalDomains": [
            "cdn",
            "www.gnu.org"
        ],
        "storage": [],
        "permissions": [
            "Discord write operations",
            "Network access"
        ]
    },
    "src/plugins/f8break": {
        "externalDomains": [
            "www.gnu.org"
        ],
        "storage": [],
        "permissions": []
    },
    "src/plugins/fakeNitro": {
        "externalDomains": [
            "media.discordapp.net",
            "www.gnu.org"
        ],
        "storage": [],
        "permissions": [
            "Network access"
        ]
    },
    "src/plugins/fakeProfileThemes": {
        "externalDomains": [
            "www.gnu.org"
        ],
        "storage": [],
        "permissions": []
    },
    "src/plugins/favEmojiFirst": {
        "externalDomains": [
            "regex101.com",
            "twemoji.maxcdn.com"
        ],
        "storage": [
            "Browser or plugin data store",
            "Persistent local storage"
        ],
        "permissions": []
    },
    "src/plugins/favGifSearch": {
        "externalDomains": [
            "regex101.com",
            "www.gnu.org"
        ],
        "storage": [],
        "permissions": []
    },
    "src/plugins/fixCodeblockGap": {
        "externalDomains": [],
        "storage": [],
        "permissions": []
    },
    "src/plugins/fixImagesQuality": {
        "externalDomains": [],
        "storage": [],
        "permissions": []
    },
    "src/plugins/fixSpotifyEmbeds.desktop": {
        "externalDomains": [
            "open.spotify.com"
        ],
        "storage": [],
        "permissions": []
    },
    "src/plugins/fixYoutubeEmbeds.desktop": {
        "externalDomains": [
            "www.youtube.com"
        ],
        "storage": [],
        "permissions": []
    },
    "src/plugins/forceOwnerCrown": {
        "externalDomains": [
            "www.gnu.org"
        ],
        "storage": [],
        "permissions": []
    },
    "src/plugins/friendInvites": {
        "externalDomains": [
            "www.gnu.org"
        ],
        "storage": [],
        "permissions": []
    },
    "src/plugins/fullSearchContext": {
        "externalDomains": [
            "www.gnu.org"
        ],
        "storage": [],
        "permissions": []
    },
    "src/plugins/fullUserInChatbox": {
        "externalDomains": [],
        "storage": [],
        "permissions": []
    },
    "src/plugins/gameActivityToggle": {
        "externalDomains": [
            "www.gnu.org"
        ],
        "storage": [],
        "permissions": []
    },
    "src/plugins/gifPaste": {
        "externalDomains": [
            "www.gnu.org"
        ],
        "storage": [],
        "permissions": []
    },
    "src/plugins/greetStickerPicker": {
        "externalDomains": [
            "www.gnu.org"
        ],
        "storage": [],
        "permissions": []
    },
    "src/plugins/hideAttachments": {
        "externalDomains": [
            "www.gnu.org"
        ],
        "storage": [
            "Browser or plugin data store"
        ],
        "permissions": []
    },
    "src/plugins/iLoveSpam": {
        "externalDomains": [
            "www.gnu.org"
        ],
        "storage": [],
        "permissions": []
    },
    "src/plugins/ignoreActivities": {
        "externalDomains": [],
        "storage": [],
        "permissions": []
    },
    "src/plugins/imageFilename": {
        "externalDomains": [],
        "storage": [],
        "permissions": []
    },
    "src/plugins/imageLink": {
        "externalDomains": [],
        "storage": [],
        "permissions": []
    },
    "src/plugins/imageZoom": {
        "externalDomains": [
            "googlechrome.github.io",
            "www.gnu.org"
        ],
        "storage": [],
        "permissions": []
    },
    "src/plugins/implicitRelationships": {
        "externalDomains": [
            "www.gnu.org"
        ],
        "storage": [],
        "permissions": [
            "Network access"
        ]
    },
    "src/plugins/ircColors": {
        "externalDomains": [
            "www.gnu.org"
        ],
        "storage": [],
        "permissions": []
    },
    "src/plugins/keepCurrentChannel": {
        "externalDomains": [
            "www.gnu.org"
        ],
        "storage": [
            "Browser or plugin data store",
            "Persistent local storage"
        ],
        "permissions": []
    },
    "src/plugins/loadingQuotes": {
        "externalDomains": [
            "www.gnu.org"
        ],
        "storage": [],
        "permissions": []
    },
    "src/plugins/memberCount": {
        "externalDomains": [
            "www.gnu.org"
        ],
        "storage": [],
        "permissions": [
            "Voice or media state access"
        ]
    },
    "src/plugins/mentionAvatars": {
        "externalDomains": [
            "www.w3.org"
        ],
        "storage": [],
        "permissions": []
    },
    "src/plugins/messageClickActions": {
        "externalDomains": [],
        "storage": [],
        "permissions": [
            "Discord write operations",
            "Network access",
            "Open external applications or URLs"
        ]
    },
    "src/plugins/messageLatency": {
        "externalDomains": [
            "www.w3.org"
        ],
        "storage": [],
        "permissions": []
    },
    "src/plugins/messageLinkEmbeds": {
        "externalDomains": [
            "www.gnu.org"
        ],
        "storage": [],
        "permissions": [
            "Discord message access",
            "Network access"
        ]
    },
    "src/plugins/messageLogger": {
        "externalDomains": [],
        "storage": [],
        "permissions": [
            "Discord message access"
        ]
    },
    "src/plugins/moreQuickReactions": {
        "externalDomains": [],
        "storage": [],
        "permissions": []
    },
    "src/plugins/musicRichPresence": {
        "externalDomains": [
            "api.listenbrainz.org",
            "coverartarchive.org",
            "listenbrainz.org",
            "musicbrainz.org",
            "picard.musicbrainz.org",
            "ws.audioscrobbler.com",
            "www.gnu.org",
            "www.last.fm"
        ],
        "storage": [],
        "permissions": [
            "Network access"
        ]
    },
    "src/plugins/mutualGroupDMs": {
        "externalDomains": [
            "www.gnu.org"
        ],
        "storage": [],
        "permissions": []
    },
    "src/plugins/newGuildSettings": {
        "externalDomains": [
            "www.gnu.org"
        ],
        "storage": [],
        "permissions": []
    },
    "src/plugins/noBlockedMessages": {
        "externalDomains": [
            "www.gnu.org"
        ],
        "storage": [],
        "permissions": [
            "Discord message access"
        ]
    },
    "src/plugins/noDeepLinks.web": {
        "externalDomains": [],
        "storage": [],
        "permissions": []
    },
    "src/plugins/noDevtoolsWarning": {
        "externalDomains": [
            "www.gnu.org"
        ],
        "storage": [],
        "permissions": []
    },
    "src/plugins/noF1": {
        "externalDomains": [
            "www.gnu.org"
        ],
        "storage": [],
        "permissions": []
    },
    "src/plugins/noMaskedUrlPaste": {
        "externalDomains": [],
        "storage": [],
        "permissions": []
    },
    "src/plugins/noMiddleClickPaste": {
        "externalDomains": [],
        "storage": [],
        "permissions": []
    },
    "src/plugins/noMosaic": {
        "externalDomains": [],
        "storage": [],
        "permissions": []
    },
    "src/plugins/noOnboardingDelay": {
        "externalDomains": [
            "www.gnu.org"
        ],
        "storage": [],
        "permissions": []
    },
    "src/plugins/noPendingCount": {
        "externalDomains": [
            "www.gnu.org"
        ],
        "storage": [],
        "permissions": []
    },
    "src/plugins/noProfileThemes": {
        "externalDomains": [
            "www.gnu.org"
        ],
        "storage": [],
        "permissions": []
    },
    "src/plugins/noReplyMention": {
        "externalDomains": [
            "www.gnu.org"
        ],
        "storage": [],
        "permissions": []
    },
    "src/plugins/noServerEmojis": {
        "externalDomains": [],
        "storage": [],
        "permissions": []
    },
    "src/plugins/noSystemBadge.discordDesktop": {
        "externalDomains": [
            "www.gnu.org"
        ],
        "storage": [],
        "permissions": []
    },
    "src/plugins/noTypingAnimation": {
        "externalDomains": [],
        "storage": [],
        "permissions": []
    },
    "src/plugins/noUnblockToJump": {
        "externalDomains": [
            "www.gnu.org"
        ],
        "storage": [],
        "permissions": []
    },
    "src/plugins/notificationVolume": {
        "externalDomains": [],
        "storage": [],
        "permissions": []
    },
    "src/plugins/onePingPerDM": {
        "externalDomains": [],
        "storage": [],
        "permissions": []
    },
    "src/plugins/openInApp": {
        "externalDomains": [
            "steamcommunity.com",
            "www.gnu.org"
        ],
        "storage": [],
        "permissions": [
            "Open external applications or URLs"
        ]
    },
    "src/plugins/overrideForumDefaults": {
        "externalDomains": [],
        "storage": [],
        "permissions": []
    },
    "src/plugins/pauseInvitesForever": {
        "externalDomains": [
            "www.gnu.org"
        ],
        "storage": [],
        "permissions": [
            "Discord write operations",
            "Network access"
        ]
    },
    "src/plugins/permissionFreeWill": {
        "externalDomains": [],
        "storage": [],
        "permissions": []
    },
    "src/plugins/permissionsViewer": {
        "externalDomains": [
            "www.gnu.org"
        ],
        "storage": [],
        "permissions": [
            "Clipboard access"
        ]
    },
    "src/plugins/petpet": {
        "externalDomains": [
            "developer.mozilla.org",
            "raw.githubusercontent.com",
            "www.gnu.org"
        ],
        "storage": [],
        "permissions": [
            "Network access"
        ]
    },
    "src/plugins/pictureInPicture": {
        "externalDomains": [],
        "storage": [],
        "permissions": []
    },
    "src/plugins/pinDms": {
        "externalDomains": [
            "regex101.com",
            "www.w3.org"
        ],
        "storage": [],
        "permissions": []
    },
    "src/plugins/plainFolderIcon": {
        "externalDomains": [
            "www.gnu.org"
        ],
        "storage": [],
        "permissions": []
    },
    "src/plugins/platformIndicators": {
        "externalDomains": [
            "www.gnu.org"
        ],
        "storage": [],
        "permissions": []
    },
    "src/plugins/previewMessage": {
        "externalDomains": [
            "www.gnu.org"
        ],
        "storage": [],
        "permissions": []
    },
    "src/plugins/quickMention": {
        "externalDomains": [
            "www.gnu.org"
        ],
        "storage": [],
        "permissions": []
    },
    "src/plugins/quickReply": {
        "externalDomains": [
            "www.gnu.org"
        ],
        "storage": [],
        "permissions": [
            "Discord message access"
        ]
    },
    "src/plugins/reactErrorDecoder": {
        "externalDomains": [
            "raw.githubusercontent.com",
            "www.gnu.org"
        ],
        "storage": [],
        "permissions": [
            "Network access"
        ]
    },
    "src/plugins/readAllNotificationsButton": {
        "externalDomains": [
            "www.gnu.org"
        ],
        "storage": [],
        "permissions": []
    },
    "src/plugins/relationshipNotifier": {
        "externalDomains": [
            "cdn.discordapp.com",
            "www.gnu.org"
        ],
        "storage": [
            "Browser or plugin data store",
            "Persistent local storage"
        ],
        "permissions": []
    },
    "src/plugins/replaceGoogleSearch": {
        "externalDomains": [
            "duckduckgo.com",
            "github.com",
            "google.com",
            "icons.duckduckgo.com",
            "search.brave.com",
            "search.yahoo.com",
            "wikipedia.org",
            "www.bing.com",
            "www.google.com",
            "www.reddit.com",
            "www.startpage.com",
            "yandex.com"
        ],
        "storage": [],
        "permissions": []
    },
    "src/plugins/replyTimestamp": {
        "externalDomains": [],
        "storage": [],
        "permissions": []
    },
    "src/plugins/revealAllSpoilers": {
        "externalDomains": [
            "www.gnu.org"
        ],
        "storage": [],
        "permissions": []
    },
    "src/plugins/reverseImageSearch": {
        "externalDomains": [
            "icons.duckduckgo.com",
            "imgops.com",
            "iqdb.org",
            "lens.google.com",
            "saucenao.com",
            "www.bing.com",
            "www.gnu.org",
            "www.tineye.com",
            "yandex.com"
        ],
        "storage": [],
        "permissions": []
    },
    "src/plugins/reviewDB": {
        "externalDomains": [
            "cdn.discordapp.com",
            "github.com",
            "manti.vendicated.dev",
            "reviewdb.mantikafasi.dev",
            "www.gnu.org"
        ],
        "storage": [
            "Browser or plugin data store"
        ],
        "permissions": [
            "Network access",
            "Open external applications or URLs"
        ]
    },
    "src/plugins/roleColorEverywhere": {
        "externalDomains": [
            "www.gnu.org"
        ],
        "storage": [],
        "permissions": []
    },
    "src/plugins/secretRingTone": {
        "externalDomains": [],
        "storage": [],
        "permissions": []
    },
    "src/plugins/seeSummaries": {
        "externalDomains": [],
        "storage": [
            "Browser or plugin data store"
        ],
        "permissions": []
    },
    "src/plugins/sendTimestamps": {
        "externalDomains": [
            "www.gnu.org"
        ],
        "storage": [],
        "permissions": []
    },
    "src/plugins/serverInfo": {
        "externalDomains": [],
        "storage": [],
        "permissions": []
    },
    "src/plugins/serverListIndicators": {
        "externalDomains": [
            "www.gnu.org",
            "www.w3.org"
        ],
        "storage": [],
        "permissions": []
    },
    "src/plugins/shikiCodeblocks.desktop": {
        "externalDomains": [
            "cdn.jsdelivr.net",
            "raw.githubusercontent.com",
            "stackoverflow.com",
            "www.gnu.org"
        ],
        "storage": [],
        "permissions": [
            "Clipboard access",
            "Network access"
        ]
    },
    "src/plugins/showAllMessageButtons": {
        "externalDomains": [],
        "storage": [],
        "permissions": []
    },
    "src/plugins/showConnections": {
        "externalDomains": [
            "www.gnu.org",
            "www.xbox.com"
        ],
        "storage": [],
        "permissions": [
            "Open external applications or URLs"
        ]
    },
    "src/plugins/showHiddenChannels": {
        "externalDomains": [
            "www.gnu.org"
        ],
        "storage": [],
        "permissions": [
            "Network access"
        ]
    },
    "src/plugins/showHiddenThings": {
        "externalDomains": [
            "www.gnu.org"
        ],
        "storage": [],
        "permissions": []
    },
    "src/plugins/showMeYourName": {
        "externalDomains": [],
        "storage": [
            "Browser or plugin data store",
            "Persistent local storage"
        ],
        "permissions": [
            "Discord message access"
        ]
    },
    "src/plugins/showTimeoutDuration": {
        "externalDomains": [],
        "storage": [],
        "permissions": []
    },
    "src/plugins/silentMessageToggle": {
        "externalDomains": [
            "www.gnu.org"
        ],
        "storage": [],
        "permissions": []
    },
    "src/plugins/silentTyping": {
        "externalDomains": [
            "www.gnu.org",
            "www.w3.org"
        ],
        "storage": [],
        "permissions": [
            "Discord message access"
        ]
    },
    "src/plugins/sortFriendRequests": {
        "externalDomains": [
            "www.gnu.org",
            "www.w3.org"
        ],
        "storage": [],
        "permissions": []
    },
    "src/plugins/spotifyCrack": {
        "externalDomains": [
            "www.gnu.org"
        ],
        "storage": [],
        "permissions": []
    },
    "src/plugins/spotifyShareCommands": {
        "externalDomains": [
            "open.spotify.com",
            "www.gnu.org"
        ],
        "storage": [],
        "permissions": []
    },
    "src/plugins/startupTimings": {
        "externalDomains": [
            "www.gnu.org"
        ],
        "storage": [],
        "permissions": []
    },
    "src/plugins/stickerPaste": {
        "externalDomains": [],
        "storage": [],
        "permissions": []
    },
    "src/plugins/streamerModeOnStream": {
        "externalDomains": [
            "www.gnu.org"
        ],
        "storage": [],
        "permissions": []
    },
    "src/plugins/superReactionTweaks": {
        "externalDomains": [],
        "storage": [],
        "permissions": []
    },
    "src/plugins/tenorGifSearch": {
        "externalDomains": [
            "api.tenor.com"
        ],
        "storage": [],
        "permissions": [
            "Network access"
        ]
    },
    "src/plugins/textReplace": {
        "externalDomains": [
            "www.gnu.org"
        ],
        "storage": [],
        "permissions": []
    },
    "src/plugins/themeAttributes": {
        "externalDomains": [],
        "storage": [],
        "permissions": []
    },
    "src/plugins/translate": {
        "externalDomains": [
            "api-free.deepl.com",
            "api.deepl.com",
            "translate-pa.googleapis.com",
            "translate.google.com",
            "translate.kagi.com",
            "www.gnu.org"
        ],
        "storage": [],
        "permissions": [
            "Local filesystem access",
            "Network access"
        ]
    },
    "src/plugins/typingIndicator": {
        "externalDomains": [
            "www.gnu.org"
        ],
        "storage": [],
        "permissions": []
    },
    "src/plugins/typingTweaks": {
        "externalDomains": [
            "www.gnu.org"
        ],
        "storage": [],
        "permissions": []
    },
    "src/plugins/unindent": {
        "externalDomains": [
            "www.gnu.org"
        ],
        "storage": [],
        "permissions": []
    },
    "src/plugins/unlockedAvatarZoom": {
        "externalDomains": [],
        "storage": [],
        "permissions": []
    },
    "src/plugins/unsuppressEmbeds": {
        "externalDomains": [
            "www.gnu.org"
        ],
        "storage": [],
        "permissions": [
            "Discord write operations",
            "Network access"
        ]
    },
    "src/plugins/userMessagesPronouns": {
        "externalDomains": [
            "www.gnu.org"
        ],
        "storage": [],
        "permissions": []
    },
    "src/plugins/userVoiceShow": {
        "externalDomains": [
            "www.gnu.org"
        ],
        "storage": [],
        "permissions": [
            "Voice or media state access"
        ]
    },
    "src/plugins/usrbg": {
        "externalDomains": [
            "github.com",
            "usrbg.is-hardly.online",
            "www.gnu.org"
        ],
        "storage": [],
        "permissions": [
            "Network access",
            "Open external applications or URLs"
        ]
    },
    "src/plugins/validReply": {
        "externalDomains": [],
        "storage": [],
        "permissions": [
            "Network access"
        ]
    },
    "src/plugins/validUser": {
        "externalDomains": [
            "discord.com",
            "support-dev.discord.com",
            "support.discord.com",
            "www.gnu.org"
        ],
        "storage": [],
        "permissions": [
            "Network access"
        ]
    },
    "src/plugins/vcDoubleClick": {
        "externalDomains": [
            "www.gnu.org"
        ],
        "storage": [],
        "permissions": []
    },
    "src/plugins/vcNarrator": {
        "externalDomains": [
            "developer.mozilla.org",
            "www.gnu.org"
        ],
        "storage": [],
        "permissions": [
            "Voice or media state access"
        ]
    },
    "src/plugins/viewIcons": {
        "externalDomains": [
            "www.gnu.org"
        ],
        "storage": [],
        "permissions": []
    },
    "src/plugins/viewRaw": {
        "externalDomains": [
            "www.gnu.org"
        ],
        "storage": [],
        "permissions": [
            "Clipboard access"
        ]
    },
    "src/plugins/voiceDownload": {
        "externalDomains": [],
        "storage": [],
        "permissions": []
    },
    "src/plugins/voiceMessages": {
        "externalDomains": [
            "convertio.co",
            "www.gnu.org"
        ],
        "storage": [],
        "permissions": [
            "Discord write operations",
            "Local filesystem access",
            "Network access",
            "Voice or media state access"
        ]
    },
    "src/plugins/volumeBooster": {
        "externalDomains": [
            "developer.mozilla.org",
            "www.gnu.org"
        ],
        "storage": [],
        "permissions": [
            "Voice or media state access"
        ]
    },
    "src/plugins/webContextMenus.web": {
        "externalDomains": [
            "media.discordapp.net",
            "www.gnu.org"
        ],
        "storage": [],
        "permissions": [
            "Clipboard access",
            "Network access"
        ]
    },
    "src/plugins/webKeybinds.web": {
        "externalDomains": [
            "www.gnu.org"
        ],
        "storage": [],
        "permissions": []
    },
    "src/plugins/webScreenShareFixes.web": {
        "externalDomains": [],
        "storage": [],
        "permissions": []
    },
    "src/plugins/whoReacted": {
        "externalDomains": [
            "www.gnu.org"
        ],
        "storage": [],
        "permissions": [
            "Network access"
        ]
    },
    "src/plugins/xsOverlay": {
        "externalDomains": [
            "cdn.discordapp.com"
        ],
        "storage": [],
        "permissions": [
            "Discord message access",
            "Network access"
        ]
    },
    "src/plugins/youtubeAdblock.desktop": {
        "externalDomains": [
            "github.com",
            "www.gnu.org",
            "www.youtube.com"
        ],
        "storage": [],
        "permissions": []
    },
    "src/equicordplugins/_api": {
        "externalDomains": [],
        "storage": [],
        "permissions": []
    },
    "src/equicordplugins/_core": {
        "externalDomains": [],
        "storage": [],
        "permissions": []
    },
    "src/equicordplugins/advancedPermissions": {
        "externalDomains": [],
        "storage": [],
        "permissions": []
    },
    "src/equicordplugins/altKrispSwitch": {
        "externalDomains": [],
        "storage": [],
        "permissions": []
    },
    "src/equicordplugins/alwaysExpandProfiles": {
        "externalDomains": [],
        "storage": [],
        "permissions": []
    },
    "src/equicordplugins/animalese": {
        "externalDomains": [
            "raw.githubusercontent.com"
        ],
        "storage": [],
        "permissions": [
            "Discord message access",
            "Network access"
        ]
    },
    "src/equicordplugins/atSomeone": {
        "externalDomains": [],
        "storage": [],
        "permissions": []
    },
    "src/equicordplugins/autoCodeblockLanguage.desktop": {
        "externalDomains": [],
        "storage": [],
        "permissions": []
    },
    "src/equicordplugins/autoZipper": {
        "externalDomains": [],
        "storage": [],
        "permissions": []
    },
    "src/equicordplugins/bannersEverywhere": {
        "externalDomains": [
            "cdn.discordapp.com"
        ],
        "storage": [
            "Browser or plugin data store",
            "Persistent local storage"
        ],
        "permissions": []
    },
    "src/equicordplugins/baseDecoder": {
        "externalDomains": [
            "www.gnu.org",
            "www.w3.org"
        ],
        "storage": [],
        "permissions": [
            "Clipboard access"
        ]
    },
    "src/equicordplugins/betterActivities": {
        "externalDomains": [
            "cdn.discordapp.com",
            "discord.com",
            "i.scdn.co",
            "media.discordapp.net",
            "www.w3.org"
        ],
        "storage": [],
        "permissions": [
            "Network access"
        ]
    },
    "src/equicordplugins/betterAudioPlayer": {
        "externalDomains": [
            "cors.keiran0.workers.dev"
        ],
        "storage": [],
        "permissions": [
            "Network access"
        ]
    },
    "src/equicordplugins/betterBanReasons": {
        "externalDomains": [],
        "storage": [],
        "permissions": []
    },
    "src/equicordplugins/betterBlockedUsers": {
        "externalDomains": [],
        "storage": [],
        "permissions": []
    },
    "src/equicordplugins/betterCommands": {
        "externalDomains": [],
        "storage": [],
        "permissions": []
    },
    "src/equicordplugins/betterForwards": {
        "externalDomains": [],
        "storage": [],
        "permissions": []
    },
    "src/equicordplugins/betterInvites": {
        "externalDomains": [
            "cdn.discordapp.com"
        ],
        "storage": [],
        "permissions": []
    },
    "src/equicordplugins/betterPlusReacts": {
        "externalDomains": [],
        "storage": [],
        "permissions": [
            "Discord message access"
        ]
    },
    "src/equicordplugins/blockKeywords": {
        "externalDomains": [
            "stackoverflow.com"
        ],
        "storage": [],
        "permissions": [
            "Discord message access"
        ]
    },
    "src/equicordplugins/blockKrisp": {
        "externalDomains": [],
        "storage": [],
        "permissions": []
    },
    "src/equicordplugins/bypassPinPrompt": {
        "externalDomains": [],
        "storage": [],
        "permissions": []
    },
    "src/equicordplugins/bypassStatus": {
        "externalDomains": [],
        "storage": [],
        "permissions": [
            "Discord message access"
        ]
    },
    "src/equicordplugins/channelBadges": {
        "externalDomains": [],
        "storage": [],
        "permissions": []
    },
    "src/equicordplugins/channelTabs": {
        "externalDomains": [
            "discord.com"
        ],
        "storage": [
            "Browser or plugin data store",
            "Persistent local storage"
        ],
        "permissions": []
    },
    "src/equicordplugins/cleanChannelName": {
        "externalDomains": [],
        "storage": [],
        "permissions": []
    },
    "src/equicordplugins/cleanerChannelGroups": {
        "externalDomains": [],
        "storage": [],
        "permissions": []
    },
    "src/equicordplugins/clickableRoles": {
        "externalDomains": [],
        "storage": [],
        "permissions": [
            "Network access"
        ]
    },
    "src/equicordplugins/clientSideBlock": {
        "externalDomains": [],
        "storage": [],
        "permissions": []
    },
    "src/equicordplugins/clientsideGuildIcons": {
        "externalDomains": [],
        "storage": [
            "Browser or plugin data store"
        ],
        "permissions": [
            "Network access"
        ]
    },
    "src/equicordplugins/clipUpload.desktop": {
        "externalDomains": [
            "cdn.jsdelivr.net",
            "discord.com"
        ],
        "storage": [
            "Persistent local storage"
        ],
        "permissions": [
            "Discord write operations",
            "Local filesystem access",
            "Network access",
            "Voice or media state access"
        ]
    },
    "src/equicordplugins/clipsEnhancements.discordDesktop": {
        "externalDomains": [],
        "storage": [],
        "permissions": []
    },
    "src/equicordplugins/collapsibleUi": {
        "externalDomains": [],
        "storage": [],
        "permissions": []
    },
    "src/equicordplugins/commandPalette": {
        "externalDomains": [],
        "storage": [
            "Browser or plugin data store",
            "Persistent local storage"
        ],
        "permissions": [
            "Clipboard access",
            "Open external applications or URLs"
        ]
    },
    "src/equicordplugins/contentWarning": {
        "externalDomains": [],
        "storage": [
            "Browser or plugin data store",
            "Persistent local storage"
        ],
        "permissions": []
    },
    "src/equicordplugins/controlPanel.desktop": {
        "externalDomains": [
            "127.0.0.1",
            "cdn.discordapp.com",
            "discord.com"
        ],
        "storage": [
            "Persistent local storage"
        ],
        "permissions": [
            "Clipboard access",
            "Discord message access",
            "Local filesystem access",
            "Network access",
            "Open external applications or URLs"
        ]
    },
    "src/equicordplugins/copyAttachmentLinks": {
        "externalDomains": [],
        "storage": [],
        "permissions": []
    },
    "src/equicordplugins/copyChannelMention": {
        "externalDomains": [],
        "storage": [],
        "permissions": [
            "Clipboard access"
        ]
    },
    "src/equicordplugins/copyMessageTimestamp": {
        "externalDomains": [],
        "storage": [],
        "permissions": [
            "Clipboard access"
        ]
    },
    "src/equicordplugins/copyProfileColors": {
        "externalDomains": [
            "www.w3.org"
        ],
        "storage": [],
        "permissions": [
            "Clipboard access"
        ]
    },
    "src/equicordplugins/copyRoleMention": {
        "externalDomains": [],
        "storage": [],
        "permissions": [
            "Clipboard access"
        ]
    },
    "src/equicordplugins/copyStatusUrls": {
        "externalDomains": [],
        "storage": [],
        "permissions": [
            "Clipboard access"
        ]
    },
    "src/equicordplugins/copyUserMediaUrls": {
        "externalDomains": [
            "cdn.discordapp.com"
        ],
        "storage": [],
        "permissions": [
            "Clipboard access"
        ]
    },
    "src/equicordplugins/copyUserMention": {
        "externalDomains": [],
        "storage": [],
        "permissions": [
            "Clipboard access"
        ]
    },
    "src/equicordplugins/cursorBuddy": {
        "externalDomains": [
            "github.com",
            "raw.githubusercontent.com"
        ],
        "storage": [
            "Browser or plugin data store"
        ],
        "permissions": []
    },
    "src/equicordplugins/customFolderIcons": {
        "externalDomains": [],
        "storage": [],
        "permissions": []
    },
    "src/equicordplugins/customSounds": {
        "externalDomains": [
            "canary.discord.com"
        ],
        "storage": [
            "Browser or plugin data store"
        ],
        "permissions": []
    },
    "src/equicordplugins/customStatusTimeouts": {
        "externalDomains": [],
        "storage": [],
        "permissions": []
    },
    "src/equicordplugins/customTimestamps": {
        "externalDomains": [
            "momentjs.com"
        ],
        "storage": [],
        "permissions": []
    },
    "src/equicordplugins/customUserColors": {
        "externalDomains": [],
        "storage": [
            "Browser or plugin data store"
        ],
        "permissions": []
    },
    "src/equicordplugins/declutter": {
        "externalDomains": [],
        "storage": [],
        "permissions": []
    },
    "src/equicordplugins/disableCameras": {
        "externalDomains": [],
        "storage": [],
        "permissions": []
    },
    "src/equicordplugins/discordDevBanner": {
        "externalDomains": [],
        "storage": [],
        "permissions": []
    },
    "src/equicordplugins/discordMcp.desktop": {
        "externalDomains": [],
        "storage": [
            "Persistent local storage"
        ],
        "permissions": [
            "Discord message access",
            "Discord write operations",
            "Local filesystem access",
            "Network access"
        ]
    },
    "src/equicordplugins/downloadAllAttachments": {
        "externalDomains": [],
        "storage": [],
        "permissions": [
            "Network access"
        ]
    },
    "src/equicordplugins/dragFavoriteEmotes": {
        "externalDomains": [
            "www.gnu.org"
        ],
        "storage": [],
        "permissions": []
    },
    "src/equicordplugins/dragify": {
        "externalDomains": [
            "discord.com",
            "discord.gg",
            "www.w3.org"
        ],
        "storage": [],
        "permissions": [
            "Discord write operations",
            "Network access",
            "Voice or media state access"
        ]
    },
    "src/equicordplugins/elementHighlighter.dev": {
        "externalDomains": [],
        "storage": [],
        "permissions": [
            "Clipboard access"
        ]
    },
    "src/equicordplugins/equibopStreamFixes.equibop": {
        "externalDomains": [],
        "storage": [
            "Browser or plugin data store"
        ],
        "permissions": []
    },
    "src/equicordplugins/equicordHelper": {
        "externalDomains": [
            "equicord.org",
            "store.epicgames.com",
            "vencord.dev",
            "www.xbox.com"
        ],
        "storage": [],
        "permissions": [
            "Voice or media state access"
        ]
    },
    "src/equicordplugins/equicordToolbox": {
        "externalDomains": [
            "discord.com",
            "www.gnu.org"
        ],
        "storage": [],
        "permissions": []
    },
    "src/equicordplugins/exitSounds": {
        "externalDomains": [],
        "storage": [],
        "permissions": [
            "Discord write operations",
            "Network access",
            "Voice or media state access"
        ]
    },
    "src/equicordplugins/exportMessages": {
        "externalDomains": [],
        "storage": [],
        "permissions": [
            "Clipboard access",
            "Network access"
        ]
    },
    "src/equicordplugins/fastDeleteChannels": {
        "externalDomains": [],
        "storage": [],
        "permissions": [
            "Discord write operations",
            "Network access"
        ]
    },
    "src/equicordplugins/favouriteAnything": {
        "externalDomains": [
            "docs.discord.food",
            "example.org",
            "github.com",
            "images-ext-1.discordapp.net",
            "placehold.jp"
        ],
        "storage": [],
        "permissions": [
            "Discord write operations",
            "Network access"
        ]
    },
    "src/equicordplugins/fileUpload": {
        "externalDomains": [
            "0x0.st",
            "api.e-z.host",
            "buzzheavier.com",
            "catbox.moe",
            "cdn.example.com",
            "cdn.jsdelivr.net",
            "codeberg.org",
            "cors.keiran0.workers.dev",
            "discord.nfp.is",
            "encrypting.host",
            "filebin.net",
            "gofile.io",
            "litterbox.catbox.moe",
            "nest.rip",
            "nextcloud.example.com",
            "pixeldrain.com",
            "pixelvault.co",
            "temp.sh",
            "tmpfiles.org",
            "upload.gofile.io",
            "w.buzzheavier.com",
            "your-cors-proxy.example.com",
            "your-endpoint.example.com",
            "your-zipline-instance.com"
        ],
        "storage": [
            "Persistent local storage"
        ],
        "permissions": [
            "Clipboard access",
            "Local filesystem access",
            "Network access"
        ]
    },
    "src/equicordplugins/findReply": {
        "externalDomains": [
            "stackoverflow.com",
            "www.gnu.org"
        ],
        "storage": [],
        "permissions": [
            "Discord message access"
        ]
    },
    "src/equicordplugins/fixFileExtensions": {
        "externalDomains": [],
        "storage": [],
        "permissions": [
            "Local filesystem access"
        ]
    },
    "src/equicordplugins/followVoiceUser": {
        "externalDomains": [],
        "storage": [],
        "permissions": [
            "Voice or media state access"
        ]
    },
    "src/equicordplugins/fontLoader": {
        "externalDomains": [
            "fonts.google.com",
            "fonts.googleapis.com"
        ],
        "storage": [],
        "permissions": [
            "Network access"
        ]
    },
    "src/equicordplugins/frequentQuickSwitcher": {
        "externalDomains": [],
        "storage": [],
        "permissions": []
    },
    "src/equicordplugins/friendCodes": {
        "externalDomains": [
            "discord.gg"
        ],
        "storage": [],
        "permissions": [
            "Clipboard access"
        ]
    },
    "src/equicordplugins/friendTags": {
        "externalDomains": [],
        "storage": [
            "Browser or plugin data store",
            "Persistent local storage"
        ],
        "permissions": []
    },
    "src/equicordplugins/friendshipRanks": {
        "externalDomains": [
            "equicord.org"
        ],
        "storage": [],
        "permissions": []
    },
    "src/equicordplugins/fullVcPfp": {
        "externalDomains": [],
        "storage": [],
        "permissions": [
            "Voice or media state access"
        ]
    },
    "src/equicordplugins/ghosted": {
        "externalDomains": [
            "cdn.discordapp.com",
            "www.w3.org"
        ],
        "storage": [],
        "permissions": [
            "Discord message access"
        ]
    },
    "src/equicordplugins/gifCollections": {
        "externalDomains": [
            "c.tenor.com",
            "cdn.discordapp.com",
            "discord.com",
            "images-ext-1.discordapp.net",
            "images-ext-2.discordapp.net",
            "media.discordapp.net"
        ],
        "storage": [
            "Browser or plugin data store",
            "Persistent local storage"
        ],
        "permissions": [
            "Clipboard access",
            "Discord message access",
            "Discord write operations",
            "Local filesystem access",
            "Network access"
        ]
    },
    "src/equicordplugins/gifMaker": {
        "externalDomains": [
            "fonts.google.com",
            "fonts.googleapis.com",
            "github.com",
            "i.giphy.com",
            "stackoverflow.com"
        ],
        "storage": [],
        "permissions": [
            "Network access"
        ]
    },
    "src/equicordplugins/githubRepos": {
        "externalDomains": [
            "api.github.com",
            "cdn.jsdelivr.net",
            "github.com",
            "www.w3.org"
        ],
        "storage": [],
        "permissions": [
            "Network access"
        ]
    },
    "src/equicordplugins/globalBadges": {
        "externalDomains": [
            "badges.equicord.org"
        ],
        "storage": [],
        "permissions": [
            "Network access"
        ]
    },
    "src/equicordplugins/googleThat": {
        "externalDomains": [
            "duckduckgo.com",
            "letmegooglethat.com",
            "search.aol.com",
            "search.yahoo.com",
            "www.ask.com",
            "www.baidu.com",
            "www.bing.com",
            "www.ecosia.org",
            "www.google.com",
            "yandex.com"
        ],
        "storage": [],
        "permissions": []
    },
    "src/equicordplugins/guildPickerDumper": {
        "externalDomains": [],
        "storage": [],
        "permissions": [
            "Network access"
        ]
    },
    "src/equicordplugins/hideChatButtons": {
        "externalDomains": [],
        "storage": [],
        "permissions": []
    },
    "src/equicordplugins/hideMessages": {
        "externalDomains": [],
        "storage": [],
        "permissions": []
    },
    "src/equicordplugins/hideServers": {
        "externalDomains": [],
        "storage": [
            "Browser or plugin data store",
            "Persistent local storage"
        ],
        "permissions": []
    },
    "src/equicordplugins/homeTyping": {
        "externalDomains": [],
        "storage": [],
        "permissions": []
    },
    "src/equicordplugins/hopOn": {
        "externalDomains": [],
        "storage": [],
        "permissions": [
            "Discord message access",
            "Open external applications or URLs"
        ]
    },
    "src/equicordplugins/husk": {
        "externalDomains": [
            "www.gnu.org"
        ],
        "storage": [],
        "permissions": [
            "Discord write operations",
            "Network access"
        ]
    },
    "src/equicordplugins/iRememberYou": {
        "externalDomains": [],
        "storage": [
            "Browser or plugin data store",
            "Persistent local storage"
        ],
        "permissions": [
            "Clipboard access",
            "Discord message access"
        ]
    },
    "src/equicordplugins/iconViewer": {
        "externalDomains": [],
        "storage": [],
        "permissions": []
    },
    "src/equicordplugins/idleAutoRestart": {
        "externalDomains": [],
        "storage": [],
        "permissions": [
            "Voice or media state access"
        ]
    },
    "src/equicordplugins/ignoreCalls": {
        "externalDomains": [],
        "storage": [],
        "permissions": []
    },
    "src/equicordplugins/inRole": {
        "externalDomains": [],
        "storage": [],
        "permissions": []
    },
    "src/equicordplugins/ingtoninator": {
        "externalDomains": [
            "www.w3.org"
        ],
        "storage": [],
        "permissions": []
    },
    "src/equicordplugins/instantScreenshare": {
        "externalDomains": [],
        "storage": [],
        "permissions": [
            "Voice or media state access"
        ]
    },
    "src/equicordplugins/invisibleChat.desktop": {
        "externalDomains": [
            "embed.sammcheese.net",
            "github.com",
            "www.gnu.org"
        ],
        "storage": [],
        "permissions": [
            "Discord write operations",
            "Network access"
        ]
    },
    "src/equicordplugins/inviteDefaults": {
        "externalDomains": [],
        "storage": [],
        "permissions": []
    },
    "src/equicordplugins/jumpTo": {
        "externalDomains": [],
        "storage": [],
        "permissions": [
            "Network access"
        ]
    },
    "src/equicordplugins/keyboardNavigation": {
        "externalDomains": [],
        "storage": [],
        "permissions": [
            "Clipboard access",
            "Network access",
            "Open external applications or URLs"
        ]
    },
    "src/equicordplugins/keyboardSounds": {
        "externalDomains": [
            "github.com"
        ],
        "storage": [],
        "permissions": []
    },
    "src/equicordplugins/keywordNotify": {
        "externalDomains": [],
        "storage": [
            "Browser or plugin data store",
            "Persistent local storage"
        ],
        "permissions": [
            "Discord message access"
        ]
    },
    "src/equicordplugins/lastActive": {
        "externalDomains": [
            "www.w3.org"
        ],
        "storage": [],
        "permissions": [
            "Network access"
        ]
    },
    "src/equicordplugins/limitlessScreenshare": {
        "externalDomains": [],
        "storage": [],
        "permissions": [
            "Voice or media state access"
        ]
    },
    "src/equicordplugins/loginWithQR": {
        "externalDomains": [
            "easings.net",
            "github.com"
        ],
        "storage": [],
        "permissions": [
            "Clipboard access",
            "Discord write operations",
            "Network access"
        ]
    },
    "src/equicordplugins/markdownTables": {
        "externalDomains": [],
        "storage": [],
        "permissions": []
    },
    "src/equicordplugins/mediaPlaybackSpeed": {
        "externalDomains": [
            "www.w3.org"
        ],
        "storage": [],
        "permissions": []
    },
    "src/equicordplugins/messageBurst": {
        "externalDomains": [],
        "storage": [],
        "permissions": [
            "Discord message access"
        ]
    },
    "src/equicordplugins/messageColors": {
        "externalDomains": [
            "en.wikipedia.org"
        ],
        "storage": [],
        "permissions": []
    },
    "src/equicordplugins/messageFetchTimer": {
        "externalDomains": [],
        "storage": [],
        "permissions": [
            "Discord message access",
            "Network access"
        ]
    },
    "src/equicordplugins/messageLinkTooltip": {
        "externalDomains": [],
        "storage": [],
        "permissions": [
            "Discord message access",
            "Network access"
        ]
    },
    "src/equicordplugins/messageLoggerEnhanced": {
        "externalDomains": [
            "github.com",
            "www.gnu.org"
        ],
        "storage": [
            "Browser or plugin data store",
            "Persistent local storage"
        ],
        "permissions": [
            "Discord message access",
            "Local filesystem access",
            "Network access"
        ]
    },
    "src/equicordplugins/messageNotifier": {
        "externalDomains": [],
        "storage": [],
        "permissions": [
            "Discord message access"
        ]
    },
    "src/equicordplugins/messagePeek": {
        "externalDomains": [],
        "storage": [],
        "permissions": [
            "Discord message access"
        ]
    },
    "src/equicordplugins/messageTranslate": {
        "externalDomains": [
            "translate.googleapis.com"
        ],
        "storage": [],
        "permissions": [
            "Discord message access",
            "Network access"
        ]
    },
    "src/equicordplugins/micLoopbackTester": {
        "externalDomains": [],
        "storage": [],
        "permissions": [
            "Voice or media state access"
        ]
    },
    "src/equicordplugins/middleClickTweaks": {
        "externalDomains": [],
        "storage": [],
        "permissions": [
            "Clipboard access"
        ]
    },
    "src/equicordplugins/moreCommands": {
        "externalDomains": [
            "api.thecatapi.com",
            "api.thedogapi.com",
            "cdn.discordapp.com",
            "nekos.best",
            "support.discord.com",
            "www.gnu.org",
            "www.reddit.com"
        ],
        "storage": [],
        "permissions": [
            "Network access"
        ]
    },
    "src/equicordplugins/moreStickers": {
        "externalDomains": [
            "cdn.jsdelivr.net",
            "cors.keiran0.workers.dev",
            "discord.com",
            "github.com",
            "store.line.me",
            "www.w3.org"
        ],
        "storage": [
            "Browser or plugin data store",
            "Persistent local storage"
        ],
        "permissions": [
            "Discord write operations",
            "Local filesystem access",
            "Network access",
            "Open external applications or URLs"
        ]
    },
    "src/equicordplugins/moreUserTags": {
        "externalDomains": [],
        "storage": [],
        "permissions": []
    },
    "src/equicordplugins/moyai": {
        "externalDomains": [
            "github.com",
            "www.gnu.org"
        ],
        "storage": [],
        "permissions": [
            "Discord message access"
        ]
    },
    "src/equicordplugins/musicControls": {
        "externalDomains": [
            "api.spotify.com",
            "fonts.google.com",
            "github.com",
            "localhost",
            "lrclib.net",
            "open.spotify.com",
            "spotify-lyrics-api-pi.vercel.app",
            "stackoverflow.com",
            "tidal.com",
            "translate.googleapis.com",
            "www.gnu.org",
            "www.tidal.com",
            "www.w3.org"
        ],
        "storage": [
            "Browser or plugin data store",
            "Persistent local storage"
        ],
        "permissions": [
            "Local filesystem access",
            "Network access",
            "Open external applications or URLs"
        ]
    },
    "src/equicordplugins/neverPausePreviews": {
        "externalDomains": [
            "www.gnu.org"
        ],
        "storage": [],
        "permissions": []
    },
    "src/equicordplugins/newPluginsManager": {
        "externalDomains": [
            "github.com"
        ],
        "storage": [
            "Browser or plugin data store",
            "Persistent local storage"
        ],
        "permissions": []
    },
    "src/equicordplugins/noNitroUpsell": {
        "externalDomains": [],
        "storage": [],
        "permissions": []
    },
    "src/equicordplugins/noPushToTalk": {
        "externalDomains": [],
        "storage": [],
        "permissions": []
    },
    "src/equicordplugins/noRPC.discordDesktop": {
        "externalDomains": [],
        "storage": [],
        "permissions": []
    },
    "src/equicordplugins/noRoleHeaders": {
        "externalDomains": [],
        "storage": [],
        "permissions": []
    },
    "src/equicordplugins/normalizeMessageLinks": {
        "externalDomains": [],
        "storage": [],
        "permissions": []
    },
    "src/equicordplugins/notificationTitle.discordDesktop": {
        "externalDomains": [],
        "storage": [],
        "permissions": []
    },
    "src/equicordplugins/orbolayBridge": {
        "externalDomains": [],
        "storage": [],
        "permissions": [
            "Network access",
            "Voice or media state access"
        ]
    },
    "src/equicordplugins/partyMode": {
        "externalDomains": [
            "www.gnu.org"
        ],
        "storage": [],
        "permissions": []
    },
    "src/equicordplugins/pendingFriendRequest": {
        "externalDomains": [],
        "storage": [],
        "permissions": []
    },
    "src/equicordplugins/persistentAudioPlayback": {
        "externalDomains": [],
        "storage": [],
        "permissions": []
    },
    "src/equicordplugins/pinIcon": {
        "externalDomains": [
            "www.gnu.org"
        ],
        "storage": [],
        "permissions": []
    },
    "src/equicordplugins/pingNotifications": {
        "externalDomains": [],
        "storage": [],
        "permissions": [
            "Discord message access"
        ]
    },
    "src/equicordplugins/platformSpoofer": {
        "externalDomains": [],
        "storage": [],
        "permissions": []
    },
    "src/equicordplugins/polishWording": {
        "externalDomains": [
            "devina.io"
        ],
        "storage": [],
        "permissions": []
    },
    "src/equicordplugins/primaryStreamAudio": {
        "externalDomains": [],
        "storage": [],
        "permissions": []
    },
    "src/equicordplugins/profileSets": {
        "externalDomains": [
            "cdn.discordapp.com"
        ],
        "storage": [
            "Browser or plugin data store",
            "Persistent local storage"
        ],
        "permissions": [
            "Local filesystem access",
            "Network access"
        ]
    },
    "src/equicordplugins/questify": {
        "externalDomains": [],
        "storage": [],
        "permissions": [
            "Discord write operations",
            "Network access"
        ]
    },
    "src/equicordplugins/quickThemeSwitcher.discordDesktop": {
        "externalDomains": [],
        "storage": [],
        "permissions": []
    },
    "src/equicordplugins/quoter": {
        "externalDomains": [
            "fonts.googleapis.com",
            "www.w3.org"
        ],
        "storage": [],
        "permissions": [
            "Network access"
        ]
    },
    "src/equicordplugins/randomVoice": {
        "externalDomains": [],
        "storage": [],
        "permissions": [
            "Voice or media state access"
        ]
    },
    "src/equicordplugins/recentDMSwitcher": {
        "externalDomains": [],
        "storage": [
            "Browser or plugin data store",
            "Persistent local storage"
        ],
        "permissions": []
    },
    "src/equicordplugins/remix": {
        "externalDomains": [
            "www.w3.org"
        ],
        "storage": [],
        "permissions": []
    },
    "src/equicordplugins/repeatMessages": {
        "externalDomains": [],
        "storage": [],
        "permissions": []
    },
    "src/equicordplugins/replyPingControl": {
        "externalDomains": [],
        "storage": [],
        "permissions": [
            "Discord message access"
        ]
    },
    "src/equicordplugins/richMagnetLinks": {
        "externalDomains": [
            "www.w3.org"
        ],
        "storage": [],
        "permissions": []
    },
    "src/equicordplugins/richPresence": {
        "externalDomains": [
            "abs.example.com",
            "api.stats.fm",
            "assets.ppy.sh",
            "gensokyoradio.net",
            "jellyfin.example.com",
            "media.discordapp.net",
            "navidrome.example.com",
            "raw.githubusercontent.com",
            "stats.fm",
            "ws.audioscrobbler.com"
        ],
        "storage": [],
        "permissions": [
            "Network access"
        ]
    },
    "src/equicordplugins/rpcEditor": {
        "externalDomains": [],
        "storage": [
            "Browser or plugin data store",
            "Persistent local storage"
        ],
        "permissions": []
    },
    "src/equicordplugins/saveFavoriteGIFs": {
        "externalDomains": [],
        "storage": [],
        "permissions": [
            "Network access"
        ]
    },
    "src/equicordplugins/scheduledMessages": {
        "externalDomains": [],
        "storage": [
            "Browser or plugin data store",
            "Persistent local storage"
        ],
        "permissions": [
            "Discord message access",
            "Discord write operations",
            "Network access"
        ]
    },
    "src/equicordplugins/screenRecorder.equibop": {
        "externalDomains": [],
        "storage": [],
        "permissions": []
    },
    "src/equicordplugins/searchFix": {
        "externalDomains": [
            "www.gnu.org"
        ],
        "storage": [],
        "permissions": []
    },
    "src/equicordplugins/secureMessaging.desktop": {
        "externalDomains": [
            "canary.discord.com",
            "discord.com",
            "discord.invalid",
            "ptb.discord.com"
        ],
        "storage": [
            "Persistent local storage"
        ],
        "permissions": [
            "Clipboard access",
            "Discord message access",
            "Discord write operations",
            "Local filesystem access",
            "Network access"
        ]
    },
    "src/equicordplugins/sedEnhanced": {
        "externalDomains": [],
        "storage": [],
        "permissions": [
            "Discord message access"
        ]
    },
    "src/equicordplugins/sekaiStickers": {
        "externalDomains": [
            "raw.githubusercontent.com",
            "st.ayaka.one",
            "www.w3.org"
        ],
        "storage": [],
        "permissions": []
    },
    "src/equicordplugins/serverSearch": {
        "externalDomains": [
            "www.w3.org"
        ],
        "storage": [],
        "permissions": []
    },
    "src/equicordplugins/showBadgesInChat": {
        "externalDomains": [
            "badge.equicord.org",
            "cdn.discordapp.com",
            "equicord.org"
        ],
        "storage": [],
        "permissions": []
    },
    "src/equicordplugins/showMessageEmbeds": {
        "externalDomains": [
            "www.youtube.com"
        ],
        "storage": [],
        "permissions": [
            "Discord message access",
            "Discord write operations",
            "Network access"
        ]
    },
    "src/equicordplugins/showResourceChannels": {
        "externalDomains": [],
        "storage": [],
        "permissions": []
    },
    "src/equicordplugins/showRolesInChat": {
        "externalDomains": [],
        "storage": [],
        "permissions": []
    },
    "src/equicordplugins/showSongName": {
        "externalDomains": [],
        "storage": [],
        "permissions": []
    },
    "src/equicordplugins/sidebarChat": {
        "externalDomains": [
            "www.w3.org"
        ],
        "storage": [],
        "permissions": [
            "Discord message access"
        ]
    },
    "src/equicordplugins/signature": {
        "externalDomains": [
            "www.w3.org"
        ],
        "storage": [],
        "permissions": []
    },
    "src/equicordplugins/silenceUsers": {
        "externalDomains": [],
        "storage": [],
        "permissions": [
            "Discord message access"
        ]
    },
    "src/equicordplugins/snowfall": {
        "externalDomains": [
            "www.w3.org"
        ],
        "storage": [],
        "permissions": []
    },
    "src/equicordplugins/soggy": {
        "externalDomains": [
            "equicord.org",
            "github.com"
        ],
        "storage": [],
        "permissions": []
    },
    "src/equicordplugins/songLink.desktop": {
        "externalDomains": [
            "api.song.link"
        ],
        "storage": [],
        "permissions": [
            "Network access",
            "Open external applications or URLs"
        ]
    },
    "src/equicordplugins/songSpotlight.desktop": {
        "externalDomains": [
            "dc.songspotlight.nexpid.xyz",
            "open.spotify.com"
        ],
        "storage": [
            "Browser or plugin data store",
            "Persistent local storage"
        ],
        "permissions": [
            "Clipboard access",
            "Network access"
        ]
    },
    "src/equicordplugins/splitLargeMessages": {
        "externalDomains": [],
        "storage": [],
        "permissions": [
            "Clipboard access"
        ]
    },
    "src/equicordplugins/spotifyActivityToggle": {
        "externalDomains": [],
        "storage": [],
        "permissions": [
            "Discord write operations",
            "Network access"
        ]
    },
    "src/equicordplugins/statusPresets": {
        "externalDomains": [
            "www.gnu.org"
        ],
        "storage": [],
        "permissions": []
    },
    "src/equicordplugins/statusWhileActive.desktop": {
        "externalDomains": [],
        "storage": [],
        "permissions": [
            "Voice or media state access"
        ]
    },
    "src/equicordplugins/steamStatusSync": {
        "externalDomains": [],
        "storage": [],
        "permissions": []
    },
    "src/equicordplugins/stickerBlocker": {
        "externalDomains": [
            "equicord.org"
        ],
        "storage": [
            "Browser or plugin data store"
        ],
        "permissions": []
    },
    "src/equicordplugins/stopAutoUnread": {
        "externalDomains": [],
        "storage": [],
        "permissions": []
    },
    "src/equicordplugins/streaks": {
        "externalDomains": [
            "streaks.equicord.org"
        ],
        "storage": [
            "Browser or plugin data store",
            "Persistent local storage"
        ],
        "permissions": [
            "Discord message access",
            "Network access"
        ]
    },
    "src/equicordplugins/streamingCodecDisabler": {
        "externalDomains": [],
        "storage": [],
        "permissions": [
            "Voice or media state access"
        ]
    },
    "src/equicordplugins/talkInReverse": {
        "externalDomains": [
            "www.gnu.org",
            "www.w3.org"
        ],
        "storage": [],
        "permissions": []
    },
    "src/equicordplugins/themeLibrary": {
        "externalDomains": [
            "github.com",
            "themes.equicord.org"
        ],
        "storage": [
            "Browser or plugin data store",
            "Persistent local storage"
        ],
        "permissions": [
            "Clipboard access",
            "Network access",
            "Open external applications or URLs"
        ]
    },
    "src/equicordplugins/tidalEmbeds": {
        "externalDomains": [
            "embed.tidal.com",
            "tidal.com"
        ],
        "storage": [],
        "permissions": []
    },
    "src/equicordplugins/timezones": {
        "externalDomains": [
            "github.com",
            "timezone.creations.works"
        ],
        "storage": [
            "Browser or plugin data store",
            "Persistent local storage"
        ],
        "permissions": [
            "Network access"
        ]
    },
    "src/equicordplugins/title": {
        "externalDomains": [],
        "storage": [],
        "permissions": []
    },
    "src/equicordplugins/toastNotifications": {
        "externalDomains": [],
        "storage": [],
        "permissions": [
            "Discord message access"
        ]
    },
    "src/equicordplugins/toggleVideoBind": {
        "externalDomains": [],
        "storage": [],
        "permissions": []
    },
    "src/equicordplugins/toneIndicators": {
        "externalDomains": [],
        "storage": [],
        "permissions": []
    },
    "src/equicordplugins/translatePlus": {
        "externalDomains": [
            "aiapi.serversmp.xyz",
            "raw.githubusercontent.com",
            "translate.google.com",
            "translate.googleapis.com",
            "www.gnu.org"
        ],
        "storage": [],
        "permissions": [
            "Network access"
        ]
    },
    "src/equicordplugins/triviaAI": {
        "externalDomains": [
            "openrouter.ai"
        ],
        "storage": [],
        "permissions": [
            "Discord message access",
            "Network access"
        ]
    },
    "src/equicordplugins/unitConverter": {
        "externalDomains": [
            "www.gnu.org"
        ],
        "storage": [],
        "permissions": []
    },
    "src/equicordplugins/universalMention": {
        "externalDomains": [],
        "storage": [],
        "permissions": []
    },
    "src/equicordplugins/unlimitedAccounts": {
        "externalDomains": [
            "www.gnu.org"
        ],
        "storage": [],
        "permissions": []
    },
    "src/equicordplugins/unreadBadgeCount": {
        "externalDomains": [],
        "storage": [],
        "permissions": []
    },
    "src/equicordplugins/urlHighlighter": {
        "externalDomains": [],
        "storage": [],
        "permissions": []
    },
    "src/equicordplugins/userpfp": {
        "externalDomains": [
            "ko-fi.com",
            "raw.githubusercontent.com",
            "userpfp.github.io"
        ],
        "storage": [
            "Browser or plugin data store"
        ],
        "permissions": [
            "Network access",
            "Open external applications or URLs"
        ]
    },
    "src/equicordplugins/userpluginInstaller.dev": {
        "externalDomains": [],
        "storage": [],
        "permissions": [
            "Local filesystem access",
            "Network access",
            "Open external applications or URLs"
        ]
    },
    "src/equicordplugins/vcPanelSettings": {
        "externalDomains": [],
        "storage": [],
        "permissions": []
    },
    "src/equicordplugins/voiceButtons": {
        "externalDomains": [],
        "storage": [],
        "permissions": [
            "Voice or media state access"
        ]
    },
    "src/equicordplugins/voiceChannelLog": {
        "externalDomains": [
            "cdn.discordapp.com",
            "www.w3.org"
        ],
        "storage": [],
        "permissions": [
            "Network access",
            "Voice or media state access"
        ]
    },
    "src/equicordplugins/voiceChatUtils": {
        "externalDomains": [],
        "storage": [],
        "permissions": [
            "Discord write operations",
            "Network access",
            "Voice or media state access"
        ]
    },
    "src/equicordplugins/voiceJoinMessages": {
        "externalDomains": [],
        "storage": [],
        "permissions": [
            "Discord message access",
            "Voice or media state access"
        ]
    },
    "src/equicordplugins/voiceMessageTranscriber.desktop": {
        "externalDomains": [
            "cdn.jsdelivr.net"
        ],
        "storage": [
            "Browser or plugin data store",
            "Persistent local storage"
        ],
        "permissions": [
            "Clipboard access",
            "Network access"
        ]
    },
    "src/equicordplugins/voiceRejoin": {
        "externalDomains": [],
        "storage": [
            "Browser or plugin data store",
            "Persistent local storage"
        ],
        "permissions": [
            "Voice or media state access"
        ]
    },
    "src/equicordplugins/voiceStats": {
        "externalDomains": [],
        "storage": [
            "Browser or plugin data store"
        ],
        "permissions": [
            "Voice or media state access"
        ]
    },
    "src/equicordplugins/waitForSlot": {
        "externalDomains": [
            "raw.githubusercontent.com"
        ],
        "storage": [],
        "permissions": [
            "Voice or media state access"
        ]
    },
    "src/equicordplugins/webpackTarball": {
        "externalDomains": [],
        "storage": [],
        "permissions": []
    },
    "src/equicordplugins/whitelistedEmojis": {
        "externalDomains": [],
        "storage": [
            "Browser or plugin data store",
            "Persistent local storage"
        ],
        "permissions": []
    },
    "src/equicordplugins/whosWatching": {
        "externalDomains": [],
        "storage": [],
        "permissions": []
    },
    "src/equicordplugins/wigglyText": {
        "externalDomains": [],
        "storage": [],
        "permissions": []
    },
    "src/equicordplugins/writeUpperCase": {
        "externalDomains": [],
        "storage": [],
        "permissions": []
    },
    "src/equicordplugins/zipPreview": {
        "externalDomains": [
            "cdn.discordapp.com"
        ],
        "storage": [],
        "permissions": [
            "Clipboard access",
            "Network access"
        ]
    }
};
