#!/usr/bin/node
/*
 * Vencord, a Discord client mod
 * Copyright (c) 2026 LawyerCord contributors
 * SPDX-License-Identifier: GPL-3.0-or-later
 */

import { readdir, readFile, writeFile } from "fs/promises";
import { join, relative, resolve } from "path";

const ROOTS = ["src/plugins", "src/equicordplugins"];
const OUTPUT = resolve("src/equicordplugins/controlPanel.desktop/privacyInventory.ts");
const SOURCE_EXTENSIONS = /\.(?:css|js|jsx|mjs|ts|tsx)$/u;

function compareEntries(left, right) {
    return left.name < right.name ? -1 : left.name > right.name ? 1 : 0;
}

async function filesUnder(directory) {
    const result = [];
    const entries = await readdir(directory, { withFileTypes: true });
    for (const entry of entries.sort(compareEntries)) {
        const path = join(directory, entry.name);
        if (entry.isDirectory()) result.push(...await filesUnder(path));
        else if (SOURCE_EXTENSIONS.test(entry.name)) result.push(path);
    }
    return result;
}

function domainsIn(source) {
    const domains = new Set();
    for (const match of source.matchAll(/https?:\/\/[A-Za-z0-9._~%:[\]-]+(?:\/[^\s"'`<>\\)]*)?/gu)) {
        try {
            const url = new URL(match[0].replace(/[),.;]+$/u, ""));
            if (!url.hostname.includes("${") && !["example.com", "www.example.com"].includes(url.hostname))
                domains.add(url.hostname.toLowerCase());
        } catch { }
    }
    return domains;
}

function sourceCapabilities(source) {
    const permissions = new Set();
    const storage = new Set();
    if (/\b(?:fetch|RestAPI|XMLHttpRequest|WebSocket)\b/u.test(source)) permissions.add("Network access");
    if (/\bRestAPI\.(?:post|put|patch|del)\b/u.test(source)) permissions.add("Discord write operations");
    if (/\b(?:MessageStore|getMessages|MESSAGE_CREATE)\b/u.test(source)) permissions.add("Discord message access");
    if (/\b(?:VoiceStateStore|MediaEngineStore|getUserMedia)\b/u.test(source)) permissions.add("Voice or media state access");
    if (/\b(?:clipboard|Clipboard)\b/u.test(source)) permissions.add("Clipboard access");
    if (/\b(?:shell\.open|openExternal)\b/u.test(source)) permissions.add("Open external applications or URLs");
    if (/\b(?:readFile|writeFile|mkdir|rm|rename|createWriteStream)\b/u.test(source)) permissions.add("Local filesystem access");
    if (/\b(?:DataStore|localStorage|sessionStorage|indexedDB|\bidb\b)\b/u.test(source)) storage.add("Browser or plugin data store");
    if (/\b(?:safeStorage|writeFile|DataStore\.set)\b/u.test(source)) storage.add("Persistent local storage");
    return { permissions, storage };
}

const inventory = {};
for (const root of ROOTS) {
    const entries = await readdir(root, { withFileTypes: true });
    for (const entry of entries.sort(compareEntries)) {
        if (!entry.isDirectory()) continue;
        const directory = join(root, entry.name);
        const sources = await Promise.all((await filesUnder(directory)).map(path => readFile(path, "utf8")));
        const combined = sources.join("\n");
        const capabilities = sourceCapabilities(combined);
        inventory[relative(".", directory).replaceAll("\\", "/")] = {
            externalDomains: [...domainsIn(combined)].sort(),
            storage: [...capabilities.storage].sort(),
            permissions: [...capabilities.permissions].sort(),
        };
    }
}

const output = `/*
 * Vencord, a Discord client mod
 * Copyright (c) 2026 LawyerCord contributors
 * SPDX-License-Identifier: GPL-3.0-or-later
 */

// Generated by scripts/generatePrivacyInventory.mjs. Do not edit manually.

export const SOURCE_PRIVACY_INVENTORY: Record<string, {
    externalDomains: string[];
    storage: string[];
    permissions: string[];
}> = ${JSON.stringify(inventory, null, 4)};
`;
await writeFile(OUTPUT, output);
console.log(`Wrote ${Object.keys(inventory).length} plugin privacy records to ${OUTPUT}`);
